# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
 
on:
  push:
    branches: [ "main" ]
 
jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install deps
      run: npm ci

    - name: Build React (Vite)
      run: npm run build

    - name: Deploy frontend to Nginx root
      run: |
        rsync -a --delete dist/ /var/www/app/


    - name: Deploy backend to /opt/app/current
      run: |
        rsync -a --delete server.js package*.json /opt/app/current/
        cd /opt/app/current
        npm ci --omit=dev


    - name: Restart PM2 (backend)
      run: |
        pm2 startOrReload /home/ubuntu/ecosystem.config.js || true
        pm2 save


    - name: Reload Nginx
      run: sudo systemctl reload nginx

    - name: Create .env
      run: |
        touch .env
        touch "${{ secrets.CTC_ENV }}" > .env

